// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5UiDlnOsMTUtfCNc4dGQKNS0CeWyJQ2A',
    appId: '1:619575373688:web:1dd847ba30047b1cdee28d',
    messagingSenderId: '619575373688',
    projectId: 'project-f890bbaf-d48c-4bd8-bb9',
    authDomain: 'project-f890bbaf-d48c-4bd8-bb9.firebaseapp.com',
    storageBucket: 'project-f890bbaf-d48c-4bd8-bb9.firebasestorage.app',
    measurementId: 'G-KDZYSDMDBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3hT3Fr4Hubrmdqqxkk1xL7QDI0ncoao',
    appId: '1:619575373688:android:946eb6f8abef7dbadee28d',
    messagingSenderId: '619575373688',
    projectId: 'project-f890bbaf-d48c-4bd8-bb9',
    storageBucket: 'project-f890bbaf-d48c-4bd8-bb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDU5R_thPGkd44LPx5i6WLeYplQ7AzCOg',
    appId: '1:619575373688:ios:30ece565c1baf2f3dee28d',
    messagingSenderId: '619575373688',
    projectId: 'project-f890bbaf-d48c-4bd8-bb9',
    storageBucket: 'project-f890bbaf-d48c-4bd8-bb9.firebasestorage.app',
    iosBundleId: 'com.example.ignitedsociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDU5R_thPGkd44LPx5i6WLeYplQ7AzCOg',
    appId: '1:619575373688:ios:30ece565c1baf2f3dee28d',
    messagingSenderId: '619575373688',
    projectId: 'project-f890bbaf-d48c-4bd8-bb9',
    storageBucket: 'project-f890bbaf-d48c-4bd8-bb9.firebasestorage.app',
    iosBundleId: 'com.example.ignitedsociety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5UiDlnOsMTUtfCNc4dGQKNS0CeWyJQ2A',
    appId: '1:619575373688:web:04a21a8f4506bdf1dee28d',
    messagingSenderId: '619575373688',
    projectId: 'project-f890bbaf-d48c-4bd8-bb9',
    authDomain: 'project-f890bbaf-d48c-4bd8-bb9.firebaseapp.com',
    storageBucket: 'project-f890bbaf-d48c-4bd8-bb9.firebasestorage.app',
    measurementId: 'G-KZ4623F7RX',
  );
}
